-- https://docs.snowflake.com/en/user-guide/data-integration/openflow/setup-openflow-spcs-sf

-- ============================================================
-- STEP 1: Core Snowflake Setup (OPENFLOW_ADMIN role & privileges)
-- ============================================================

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS OPENFLOW_ADMIN;
GRANT CREATE ROLE ON ACCOUNT TO ROLE OPENFLOW_ADMIN;

GRANT ROLE OPENFLOW_ADMIN TO USER USER;
ALTER USER USER SET DEFAULT_ROLE = OPENFLOW_ADMIN;
ALTER USER USER SET DEFAULT_SECONDARY_ROLES = ('ALL');


-- 1. Grant the Openflow admin role the account-level privileges it needs:
GRANT CREATE OPENFLOW DEPLOYMENT ON ACCOUNT TO ROLE OPENFLOW_ADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE OPENFLOW_ADMIN;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE OPENFLOW_ADMIN;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE OPENFLOW_ADMIN;

-- Snowflake deployments only:
GRANT CREATE COMPUTE POOL ON ACCOUNT TO ROLE OPENFLOW_ADMIN;

-- 2. Create the database and schema that will hold your gen 2 Openflow objects:
USE ROLE OPENFLOW_ADMIN;
CREATE DATABASE IF NOT EXISTS OPENFLOW_DB;
CREATE SCHEMA IF NOT EXISTS OPENFLOW_DB.RUNTIME;
CREATE WAREHOUSE IF NOT EXISTS OPENFLOW_WH 
    WAREHOUSE_SIZE = MEDIUM 
    GENERATION = '2';

-- 3. Grant the Openflow admin role the ability to create gen 2 objects in that schema:
USE ROLE ACCOUNTADMIN;

GRANT CREATE OPENFLOW RUNTIME ON SCHEMA OPENFLOW_DB.RUNTIME TO ROLE OPENFLOW_ADMIN;
GRANT CREATE OPENFLOW CONNECTOR ON SCHEMA OPENFLOW_DB.RUNTIME TO ROLE OPENFLOW_ADMIN;


-- ============================================================
-- STEP 2: Create Deployment 
-- ============================================================

USE ROLE OPENFLOW_ADMIN;

-- Create the openflow event table
CREATE EVENT TABLE IF NOT EXISTS OPENFLOW_DB.RUNTIME.OPENFLOW_EVENTS;

CREATE OPENFLOW DEPLOYMENT DEPLOYMENT_DEV
  DEPLOYMENT_TYPE = SNOWFLAKE
  EVENT_TABLE = 'OPENFLOW_DB.RUNTIME.OPENFLOW_EVENTS'
  DISPLAY_NAME = 'Openflow Dev Deployment';

SELECT SYSTEM$WAIT_FOR_OPENFLOW_DEPLOYMENT_STATUS(600, 'ACTIVE', 'DEPLOYMENT_DEV');

-- ============================================================
-- STEP 3: Create Postgres Instance PG01
-- ============================================================

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS PG_SETUP;
CREATE SCHEMA IF NOT EXISTS CONFIG;
CREATE TABLE IF NOT EXISTS CONFIG.PG_INSTANCE_INFO (HOST VARCHAR, ACCESS_ROLES VARCHAR);

CREATE POSTGRES INSTANCE PG01
  COMPUTE_FAMILY = 'STANDARD_L'
  STORAGE_SIZE_GB = 50
  AUTHENTICATION_AUTHORITY = POSTGRES
  POSTGRES_VERSION = 17
  COMMENT = 'Postgres instance for Openflow CDC connector'
  ->> INSERT INTO CONFIG.PG_INSTANCE_INFO SELECT "host", "access_roles" FROM $1;

-- Wait for PG01 to reach READY state (polls every 30s, up to 20 min)
BEGIN
  LET pg_state VARCHAR := 'CREATING';
  LET max_attempts INT := 40;
  LET attempt INT := 0;
  WHILE (:pg_state != 'READY' AND :attempt < :max_attempts) DO
    CALL SYSTEM$WAIT(30);
    DESCRIBE POSTGRES INSTANCE PG01;
    SELECT "value" INTO :pg_state FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) WHERE "property" = 'state';
    attempt := :attempt + 1;
  END WHILE;
  IF (:pg_state != 'READY') THEN
    CALL SYSTEM$ABORT('PG01 did not reach READY state within 20 minutes');
  END IF;
END;

-- Capture host information
SET PG_HOST = (SELECT CONCAT(HOST,':5432') FROM CONFIG.PG_INSTANCE_INFO);
SET PG_APPLICATION = (SELECT PARSE_JSON(ACCESS_ROLES):"application"::VARCHAR FROM CONFIG.PG_INSTANCE_INFO);
SET PG_SNOWFLAKE_ADMIN = (SELECT PARSE_JSON(ACCESS_ROLES):"snowflake_admin"::VARCHAR FROM CONFIG.PG_INSTANCE_INFO);
SELECT $PG_HOST, $PG_APPLICATION, $PG_SNOWFLAKE_ADMIN;


-- Check status:
-- DESCRIBE POSTGRES INSTANCE PG01;


-- ============================================================
-- STEP 4: Create Runtime Role & Grants
-- ============================================================

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS OPENFLOW_RUNTIME_PG_ROLE;
GRANT ROLE OPENFLOW_RUNTIME_PG_ROLE TO ROLE OPENFLOW_ADMIN;

-- Warehouse access
GRANT USAGE, OPERATE ON WAREHOUSE OPENFLOW_WH TO ROLE OPENFLOW_RUNTIME_PG_ROLE;

-- Database & schema access
GRANT USAGE ON DATABASE OPENFLOW_DB TO ROLE OPENFLOW_RUNTIME_PG_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE OPENFLOW_DB TO ROLE OPENFLOW_RUNTIME_PG_ROLE;
GRANT CREATE SCHEMA ON DATABASE OPENFLOW_DB TO ROLE OPENFLOW_RUNTIME_PG_ROLE;
GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE OPENFLOW_DB TO ROLE OPENFLOW_RUNTIME_PG_ROLE;


-- ============================================================
-- STEP 5: Create Network Rule & External Access Integration
-- ============================================================
-- PostgreSQL connector requires the customer-specific host:port

USE ROLE OPENFLOW_ADMIN;
USE DATABASE OPENFLOW_DB;
USE SCHEMA RUNTIME;

CREATE NETWORK RULE IF NOT EXISTS OPENFLOW_DB.RUNTIME.OPENFLOW_RUNTIME_PG_NETWORK_RULE
  TYPE = HOST_PORT
  MODE = EGRESS
  VALUE_LIST = ($PG_HOST);

USE ROLE ACCOUNTADMIN;

CREATE EXTERNAL ACCESS INTEGRATION IF NOT EXISTS OPENFLOW_RUNTIME_PG_EAI
  ALLOWED_NETWORK_RULES = (OPENFLOW_DB.RUNTIME.OPENFLOW_RUNTIME_PG_NETWORK_RULE)
  ENABLED = TRUE
  COMMENT = 'External Access Integration for Openflow PostgreSQL connectivity to PG01';

GRANT USAGE ON INTEGRATION OPENFLOW_RUNTIME_PG_EAI TO ROLE OPENFLOW_RUNTIME_PG_ROLE;

-- Also grant to OPENFLOW_ADMIN so the EAI is visible in the Openflow UI when creating/editing runtimes
GRANT USAGE ON INTEGRATION OPENFLOW_RUNTIME_PG_EAI TO ROLE OPENFLOW_ADMIN;


-- ============================================================
-- STEP 6: Create Runtime
-- ============================================================
USE ROLE OPENFLOW_ADMIN;
USE DATABASE OPENFLOW_DB;
USE SCHEMA RUNTIME;

CREATE OPENFLOW RUNTIME OPENFLOW_DB.RUNTIME.RUNTIME_PG
  IN DEPLOYMENT DEPLOYMENT_DEV
  NODE_TYPE = SMALL
  NODE_TYPE_TIER = 'S1'
  MIN_NODES = 1
  MAX_NODES = 1
  EXECUTE_AS_ROLE = OPENFLOW_RUNTIME_PG_ROLE
  EXTERNAL_ACCESS_INTEGRATIONS = ('OPENFLOW_RUNTIME_PG_EAI')
  DISPLAY_NAME = 'Postgres Runtime';

SELECT SYSTEM$WAIT_FOR_OPENFLOW_RUNTIME_STATUS(600, 'ACTIVE', 'RUNTIME_PG');

-- ============================================================
-- STEP 7: Configure PostgreSQL CDC Connector using Coco
-- ============================================================


-- ============================================================
-- STEP 8: Configure Destination Database (AIRLINE_OPS)
-- ============================================================
-- Account: SFSENORTHAMERICA-CA_DEMO30 (awsdemo30 in connections.toml)

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS AIRLINE_OPS
  COMMENT = 'Destination database for Openflow PostgreSQL CDC connector';

-- Grant runtime role access to write to destination
GRANT USAGE ON DATABASE AIRLINE_OPS TO ROLE OPENFLOW_RUNTIME_PG_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE AIRLINE_OPS TO ROLE OPENFLOW_RUNTIME_PG_ROLE;
GRANT CREATE SCHEMA ON DATABASE AIRLINE_OPS TO ROLE OPENFLOW_RUNTIME_PG_ROLE;
GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE AIRLINE_OPS TO ROLE OPENFLOW_RUNTIME_PG_ROLE;

-- PostgreSQL CDC mirrors source schema names (ie lowercase "public")
-- The connector needs this schema to exist before it can create tables
CREATE SCHEMA IF NOT EXISTS RESERVATIONS;
CREATE SCHEMA IF NOT EXISTS FLIGHT_OPS;

GRANT USAGE ON SCHEMA AIRLINE_OPS.RESERVATIONS TO ROLE OPENFLOW_RUNTIME_PG_ROLE;
GRANT CREATE TABLE ON SCHEMA AIRLINE_OPS.RESERVATIONS TO ROLE OPENFLOW_RUNTIME_PG_ROLE;

GRANT USAGE ON SCHEMA AIRLINE_OPS.FLIGHT_OPS TO ROLE OPENFLOW_RUNTIME_PG_ROLE;
GRANT CREATE TABLE ON SCHEMA AIRLINE_OPS.FLIGHT_OPS TO ROLE OPENFLOW_RUNTIME_PG_ROLE;


-- ============================================================
-- STEP 9: Network Policy for PG01
-- ============================================================
-- Postgres instances require MODE = POSTGRES_INGRESS network rules
-- To discover IPs: connect with 0.0.0.0/0, then run:
--   SELECT DISTINCT client_addr FROM pg_stat_activity;

USE ROLE OPENFLOW_ADMIN;

--Initially use 0.0.0.0/0 for Openflow Runtime IP then ask Coco to update with actual IP
CREATE NETWORK RULE OPENFLOW_DB.RUNTIME.PG01_INGRESS_RULE
  TYPE = IPV4
  VALUE_LIST = ('0.0.0.0/0')
  MODE = POSTGRES_INGRESS;

USE ROLE ACCOUNTADMIN;
CREATE NETWORK POLICY PG01_NETWORK_POLICY
  ALLOWED_NETWORK_RULE_LIST = ('OPENFLOW_DB.RUNTIME.PG01_INGRESS_RULE')
  COMMENT = 'Allow Openflow SPCS runtime access to PG01';

ALTER POSTGRES INSTANCE PG01 SET NETWORK_POLICY = 'PG01_NETWORK_POLICY';

-- ============================================================
-- SETUP COMPLETE: RETURN PG CONFIGURATION
-- ============================================================
SELECT $PG_HOST AS PG_HOST, 'application' AS APPLICATION_USER, $PG_APPLICATION AS APPLICATION_USER_PWD, 'snowflake_admin' DBA_USER, $PG_SNOWFLAKE_ADMIN AS DBA_PWD;


-- ============================================================
-- TEARDOWN: Drop all objects created by this script
-- ============================================================
-- Run in reverse dependency order. Uncomment to execute.

/*

USE ROLE ACCOUNTADMIN;

-- Step 9: Network policy & ingress rule
ALTER POSTGRES INSTANCE PG01 UNSET NETWORK_POLICY;
DROP NETWORK POLICY IF EXISTS PG01_NETWORK_POLICY;
DROP NETWORK RULE IF EXISTS OPENFLOW_DB.RUNTIME.PG01_INGRESS_RULE;

-- Step 8: Destination database
DROP DATABASE IF EXISTS AIRLINE_OPS;
DROP DATABASE IF EXISTS PG_SETUP;

-- Step 6: Openflow runtime (must suspend, terminate, then drop)
ALTER OPENFLOW RUNTIME IF EXISTS OPENFLOW_DB.RUNTIME.RUNTIME_PG SUSPEND;
SELECT SYSTEM$WAIT_FOR_OPENFLOW_RUNTIME_STATUS(600, 'SUSPENDED', 'OPENFLOW_DB.RUNTIME.RUNTIME_PG');
ALTER OPENFLOW RUNTIME IF EXISTS OPENFLOW_DB.RUNTIME.RUNTIME_PG TERMINATE;
SELECT SYSTEM$WAIT_FOR_OPENFLOW_RUNTIME_STATUS(600, 'TERMINATED', 'OPENFLOW_DB.RUNTIME.RUNTIME_PG');
DROP OPENFLOW RUNTIME IF EXISTS OPENFLOW_DB.RUNTIME.RUNTIME_PG;

-- Step 5: External access integration & network rule
DROP INTEGRATION IF EXISTS OPENFLOW_RUNTIME_PG_EAI;
DROP NETWORK RULE IF EXISTS OPENFLOW_DB.RUNTIME.OPENFLOW_RUNTIME_PG_NETWORK_RULE;

-- Step 4: Runtime role
DROP ROLE IF EXISTS OPENFLOW_RUNTIME_PG_ROLE;

-- Step 3: Postgres instance & setup database
DROP POSTGRES INSTANCE IF EXISTS PG01;
DROP DATABASE IF EXISTS PG_SETUP;

-- Step 2: Openflow deployment & event table
USE ROLE OPENFLOW_ADMIN;
ALTER OPENFLOW DEPLOYMENT IF EXISTS DEPLOYMENT_DEV TERMINATE;
SELECT SYSTEM$WAIT_FOR_OPENFLOW_DEPLOYMENT_STATUS(600, 'TERMINATED', 'DEPLOYMENT_DEV');
DROP OPENFLOW DEPLOYMENT IF EXISTS DEPLOYMENT_DEV;
DROP EVENT TABLE IF EXISTS OPENFLOW_DB.RUNTIME.OPENFLOW_EVENTS;

-- Step 1: Openflow infrastructure
USE ROLE ACCOUNTADMIN;
DROP WAREHOUSE IF EXISTS OPENFLOW_WH;
DROP DATABASE IF EXISTS OPENFLOW_DB;

-- Drop role
ALTER USER USER SET DEFAULT_ROLE = ACCOUNTADMIN;
DROP ROLE IF EXISTS OPENFLOW_ADMIN;

*/